/**
 * Mappings from specific dish categories to broader parent categories
 * This consolidates the ~750 ungrouped single-occurrence categories into meaningful groups
 */

export const CATEGORY_MAPPINGS: Record<string, string> = {
  // === CHICKEN DISHES ===
  'bbq-chicken': 'chicken-dishes',
  'chicken-a-la-king': 'chicken-dishes',
  // chicken-biryani moved to rice-dishes section
  'chicken-bourguignon': 'chicken-dishes',
  'chicken-broccoli-pasta': 'chicken-dishes',
  'chicken-broccoli-stir-fry': 'chicken-dishes',
  'chicken-burrito': 'chicken-dishes',
  'chicken-cacciatore': 'chicken-dishes',
  'chicken-chasseur': 'chicken-dishes',
  'chicken-chile-verde': 'chicken-dishes',
  'chicken-coconut-curry': 'chicken-dishes',
  'chicken-crepe': 'chicken-dishes',
  'chicken-curry': 'chicken-dishes',
  'chicken-cutlets': 'chicken-dishes',
  'chicken-diane': 'chicken-dishes',
  'chicken-dish': 'chicken-dishes',
  'chicken-drumsticks': 'chicken-dishes',
  'chicken-fingers': 'chicken-dishes',
  'chicken-gordita': 'chicken-dishes',
  'chicken-jus': 'chicken-dishes',
  'chicken-katsu-sandwich': 'chicken-dishes',
  'chicken-marengo': 'chicken-dishes',
  'chicken-marsala': 'chicken-dishes',
  'chicken-parm': 'chicken-dishes',
  'chicken-parm-hero': 'chicken-dishes',
  'chicken-parmesan-sandwich': 'chicken-dishes',
  'chicken-pizzaiola': 'chicken-dishes',
  'chicken-saltimbocca': 'chicken-dishes',
  'chicken-scarpariello': 'chicken-dishes',
  'chicken-schnitzel': 'chicken-dishes',
  'chicken-skewers': 'chicken-dishes',
  'chicken-skin-schmaltz': 'chicken-dishes',
  'chicken-soup-with-lettuce-ginger-and-rice': 'chicken-dishes',
  'chicken-stew': 'chicken-dishes',
  'chicken-stir-fry': 'chicken-dishes',
  'chicken-strips': 'chicken-dishes',
  'chicken-tenders': 'chicken-dishes',
  'chicken-thigh': 'chicken-dishes',
  'chicken-tikka-masala': 'chicken-dishes',
  'chicken-tinga': 'chicken-dishes',
  'chicken-tortilla-espuma-tostada': 'chicken-dishes',
  'chicken-tortilla-soup': 'chicken-dishes',
  'chicken-vesuvio': 'chicken-dishes',
  'chicken-waffle': 'chicken-dishes',
  'chicken-wing-lollipops': 'chicken-dishes',
  // chicken-wrap moved to wraps section
  'chicken-and-waffles': 'chicken-dishes',
  'chicken-and-zucchini-stir-fry': 'chicken-dishes',
  'buttermilk-fried-chicken': 'fried-chicken',
  'korean-fried-chicken': 'fried-chicken',
  'kara-age': 'fried-chicken',
  'popcorn-chicken': 'chicken-dishes',
  'smoked-chicken': 'chicken-dishes',
  'stir-fried-chicken': 'chicken-dishes',
  'teriyaki-chicken': 'chicken-dishes',
  'whole-chicken': 'chicken-dishes',

  // === BEEF DISHES ===
  'beef': 'beef-dishes',
  'beef-bone-broth': 'beef-dishes',
  'beef-brisket': 'beef-dishes',
  'beef-chow-fun': 'beef-dishes',
  'beef-lasagna': 'beef-dishes',
  'beef-rendang': 'beef-dishes',
  'beef-rice-bowl': 'beef-dishes',
  // beef-stew-soup moved to soups section
  'beef-stir-fry': 'beef-dishes',
  'beef-with-broccoli': 'beef-dishes',
  'beef-and-potato-soup': 'beef-dishes',
  'beef-and-rice': 'beef-dishes',
  'black-pepper-beef': 'beef-dishes',
  'goou-jong-beef': 'beef-dishes',
  'orange-beef': 'beef-dishes',
  'ground-beef': 'beef-dishes',
  'barbecue-brisket': 'beef-dishes',

  // === PORK DISHES ===
  'pork': 'pork-dishes',
  'pork-dish': 'pork-dishes',
  'bbq-pork': 'pork-dishes',
  'char-siu-pork': 'pork-dishes',
  'fish-fragrant-pork': 'pork-dishes',
  'kung-pao-pork': 'pork-dishes',
  'moo-shu-pork': 'pork-dishes',
  'mushu-pork': 'pork-dishes',
  'pork-belly-banh-mi': 'pork-dishes',
  'pork-bone-broth': 'pork-dishes',
  'pork-gisantes': 'pork-dishes',
  // pork-shogayaki moved to japanese-dishes section
  'pork-spare-ribs': 'pork-dishes',
  'pork-tacos': 'pork-dishes',
  'breaded-pork-chops': 'pork-dishes',
  'steamed-pork-ribs': 'pork-dishes',

  // === LAMB DISHES ===
  'lamb': 'lamb-dishes',
  'lamb-bone-broth': 'lamb-dishes',
  'lamb-chops': 'lamb-dishes',
  'lamb-curry': 'lamb-dishes',
  // lamb-kofta-wrap moved to wraps section
  'rack-of-lamb': 'lamb-dishes',
  'roasted-lamb': 'lamb-dishes',
  'moussaka': 'lamb-dishes',

  // === SEAFOOD ===
  'baked-lobster-tails': 'seafood',
  'baked-salmon': 'seafood',
  'blackened-fish': 'seafood',
  'branzino': 'seafood',
  'cataplana': 'seafood',
  'ceviche': 'seafood',
  'cioppino': 'seafood',
  'clam-spaghetti': 'seafood',
  'crab-cakes': 'seafood',
  'crab-rangoon': 'seafood',
  'flounder': 'seafood',
  'grilled-cod': 'seafood',
  'grilled-salmon': 'seafood',
  'grilled-scallops': 'seafood',
  'grilled-swordfish': 'seafood',
  'hamachi-crudo': 'seafood',
  'honey-walnut-shrimp': 'seafood',
  'lobster-fettuccine': 'seafood',
  'mustard-crusted-salmon': 'seafood',
  'oysters': 'seafood',
  'pan-seared-fish': 'seafood',
  'sea-bass': 'seafood',
  'seared-salmon': 'seafood',
  'seared-scallops': 'seafood',
  'shrimp-and-beans': 'seafood',
  'shrimp-and-grits': 'seafood',
  'shrimp-curry': 'seafood',
  'shrimp-dish': 'seafood',
  'shrimp-pasta': 'seafood',
  'shrimp-salad': 'seafood',
  'smelt': 'seafood',
  'steamed-lobster': 'seafood',
  'swordfish-milanese': 'seafood',
  'whole-lobster': 'seafood',
  'fish': 'seafood',
  'cooked-fish': 'seafood',
  'fish-stew': 'seafood',
  'gravlax': 'seafood',
  'gravlox': 'seafood',
  'lox': 'seafood',
  'crawfish-boil': 'seafood',
  'crawfish-etouffee': 'seafood',
  'gambas-al-ajillo': 'seafood',
  'bouillabaisse': 'seafood',
  'linguine-allo-scoglio': 'seafood',
  'linguini-clam-sauce': 'seafood',
  'chili-crab': 'seafood',

  // === SOUPS ===
  'beef-stew-soup': 'soups',
  'bisque': 'soups',
  'broccoli-cheddar-soup': 'soups',
  'caldo-verde': 'soups',
  'cauliflower-soup': 'soups',
  'changua': 'soups',
  'corn-and-basil-soup': 'soups',
  'corn-chowder': 'soups',
  'corn-soup': 'soups',
  'cucumber-yogurt-soup': 'soups',
  'curry-soup': 'soups',
  'egg-drop-soup': 'soups',
  'french-onion-soup': 'soups',
  'kapusniak': 'soups',
  'lentil-soup': 'soups',
  'matzo-ball-soup': 'soups',
  'polenta-soup': 'soups',
  'pumpkin-soup': 'soups',
  'split-pea-soup': 'soups',
  'spinach-soup': 'soups',
  'tom-yum-soup': 'soups',
  'tomato-soup': 'soups',
  'vegetable-soup': 'soups',
  'wonton-soup': 'soups',
  'zucchini-soup': 'soups',
  'ajiaco': 'soups',

  // === SAUCES & CONDIMENTS ===
  'aioli': 'sauces',
  'anchovy-paste': 'sauces',
  'aromatic-paste': 'sauces',
  'baja-sauce': 'sauces',
  'bbq-sauce': 'sauces',
  'bolognese-sauce': 'sauces',
  'burger-sauce': 'sauces',
  'chili-oil': 'sauces',
  'chili-sauce': 'sauces',
  'hollandaise-sauce': 'sauces',
  'habanero-salsa': 'sauces',
  'habanero-sauce': 'sauces',
  'mayo': 'sauces',
  'pan-sauce': 'sauces',
  'piperade-sauce': 'sauces',
  'port-wine-sauce': 'sauces',
  'ranch-dressing': 'sauces',
  'ranch-sauce': 'sauces',
  'red-sauce': 'sauces',
  'remoulade': 'sauces',
  'sriracha': 'sauces',
  'tomato-ragu': 'sauces',
  'vinaigrette': 'sauces',
  'vodka-sauce': 'sauces',
  'wing-sauce': 'sauces',
  'white-sauce-doner-kebab': 'sauces',
  'yogurt-sauce': 'sauces',
  'ragu-bolognese': 'sauces',
  'sausage-ragu': 'sauces',
  'curry-paste': 'sauces',
  'ketchup': 'sauces',
  'relish': 'sauces',
  'demi-glace': 'sauces',
  'roux': 'sauces',
  'compote': 'sauces',

  // === PASTA DISHES ===
  'alfredo': 'pasta',
  'baked-feta-pasta': 'pasta',
  'bucatini-all-amatriciana': 'pasta',
  'cannelloni': 'pasta',
  'cappellacci': 'pasta',
  'carbonara': 'pasta',
  'fettuccine-al-burro': 'pasta',
  'fettuccine-with-butter-and-cheese': 'pasta',
  'fettucine-alfredo': 'pasta',
  'fusilli': 'pasta',
  'handmade-pasta': 'pasta',
  'linguine-broccoli-pesto-bacon': 'pasta',
  'manicotti': 'pasta',
  'marinara-pasta': 'pasta',
  'orecchiette': 'pasta',
  'pasta-alla-carbonara': 'pasta',
  'pasta-alla-gricia': 'pasta',
  'pasta-alla-norcina': 'pasta',
  'pasta-alla-vodka': 'pasta',
  'pasta-bolognese': 'pasta',
  'pasta-cacio-e-uova': 'pasta',
  'pasta-framework': 'pasta',
  'pasta-primavera': 'pasta',
  'pasta-with-sausage-ragu': 'pasta',
  'pastitsio': 'pasta',
  'penne-all-arrabbiata': 'pasta',
  'pesto-pasta': 'pasta',
  'ricotta-pasta': 'pasta',
  'spaghetti-aglio-e-olio': 'pasta',
  'spaghetti-aglio-e-olio-e-peperoncino': 'pasta',
  'spaghetti-aglio-olio': 'pasta',
  'spaghetti-carbonara': 'pasta',
  'spaghetti-clam-sauce': 'pasta',
  'spaghetti-meatballs': 'pasta',
  'vegetable-pasta': 'pasta',
  'yuba-pasta': 'pasta',

  // === ASIAN NOODLES ===
  'biang-biang-noodles': 'asian-noodles',
  'butter-noodles': 'noodles',
  'buttered-oyster-sauce-noodles': 'asian-noodles',
  'garlic-noodles': 'asian-noodles',
  'miso-ramen': 'ramen',
  'niku-udon': 'udon-noodles',
  'pad-see-ew': 'asian-noodles',
  'peanut-noodles': 'asian-noodles',
  'scallion-oil-noodles': 'asian-noodles',
  'sesame-noodles': 'asian-noodles',
  'somen': 'asian-noodles',
  'beijing-noodles': 'asian-noodles',
  'mazemen': 'ramen',

  // === BREADS ===
  'bagel-bread': 'bread',
  'baguettes': 'bread',
  'bread-loaf': 'bread',
  'bread-rolls': 'bread',
  'brioche-burger-buns': 'bread',
  'brown-soda-bread': 'bread',
  'challah-bread': 'bread',
  'dinner-rolls': 'bread',
  'english-muffins': 'bread',
  'focaccia': 'bread',
  'hoagie-rolls': 'bread',
  'no-knead-bread': 'bread',
  'naan': 'bread',
  'rolls': 'bread',
  'shokupan': 'bread',
  'stuffed-bread': 'bread',

  // === DESSERTS ===
  'apple-crumble': 'desserts',
  'apple-gallette': 'desserts',
  'apple-pies': 'desserts',
  'apple-strudel': 'desserts',
  'apple-tart': 'desserts',
  'apple-turnovers': 'desserts',
  'banana-pudding-pie': 'desserts',
  'bark': 'desserts',
  'biscotti': 'desserts',
  'black-and-white-cookie': 'desserts',
  'blueberry-jam-cake': 'desserts',
  'brownie': 'desserts',
  'brownies': 'desserts',
  'buche-de-noel': 'desserts',
  'candy-bar': 'desserts',
  'chocolate-cupcakes': 'desserts',
  'chocolate-frosty': 'desserts',
  'chocolate-mousse': 'desserts',
  'chocolate-pies': 'desserts',
  'chocolate-roulade': 'desserts',
  'chocolate-souffle': 'desserts',
  'cobbler': 'desserts',
  'coconut-cream-pie': 'desserts',
  'creme-pies': 'desserts',
  'figgy-pudding': 'desserts',
  'flan': 'desserts',
  'frosty': 'desserts',
  'fruit-tart': 'desserts',
  'galette': 'desserts',
  'gateau-breton': 'desserts',
  'hazelnut-cookies': 'desserts',
  'ladyfingers': 'desserts',
  'lemon-curd': 'desserts',
  'lemon-olive-oil-tart': 'desserts',
  'lemon-tart': 'desserts',
  'linzertorte': 'desserts',
  'millionaires-shortbread': 'desserts',
  'olive-oil-cake': 'desserts',
  'panettone': 'desserts',
  'panna-cotta': 'desserts',
  'pastry-cream': 'desserts',
  'peach-turnover-cake': 'desserts',
  'peaches-custard': 'desserts',
  'peanut-butter-cups': 'desserts',
  'pecan-pie': 'desserts',
  'pineapple-upside-down-cake': 'desserts',
  'plum-torte': 'desserts',
  'popsicles': 'desserts',
  'pumpkin-cheesecake': 'desserts',
  'pumpkin-pie': 'desserts',
  'rugelach': 'desserts',
  'russian-tea-cakes': 'desserts',
  'sachertorte': 'desserts',
  'smores': 'desserts',
  'sorbet': 'desserts',
  'sticky-buns': 'desserts',
  'strawberry-shortcake': 'desserts',
  'strawberry-shortcakes': 'desserts',
  'strawberry-tart': 'desserts',
  'strudel': 'desserts',
  'sugar-cookies': 'desserts',
  'tart': 'desserts',
  'tarte-tatin': 'desserts',
  'cinnamon-rolls': 'desserts',
  'gingersnap-cookies': 'desserts',
  'kolaches': 'desserts',
  'stollen': 'desserts',
  'taiyaki': 'desserts',

  // === BEVERAGES ===
  'arnold-palmer-lemonade': 'beverages',
  'baja-blast': 'beverages',
  'beermosa': 'beverages',
  'beverage': 'beverages',
  'cold-brew-coffee': 'beverages',
  'daiquiri': 'beverages',
  'espresso': 'beverages',
  'gimlet': 'beverages',
  'ginger-beer': 'beverages',
  'go-gurt': 'beverages',
  'latte': 'beverages',
  'lemonade': 'beverages',
  'margarita': 'beverages',
  'mimosa': 'beverages',
  'mojito': 'beverages',
  'root-beer': 'beverages',
  'sake': 'beverages',
  'slushie': 'beverages',
  'soda': 'beverages',
  'tea': 'beverages',
  'whiskey-sour': 'beverages',
  'cocktails': 'beverages',
  'eggnog': 'beverages',

  // === STEAKS ===
  'flat-iron-steaks': 'steak',
  'french-steak': 'steak',
  'grilled-skirt-steak': 'steak',
  'grilled-steak': 'steak',
  'pan-seared-flank-steak': 'steak',
  'pan-seared-steak': 'steak',
  'picanha-steak': 'steak',
  'ribeye-steak': 'steak',
  'salisbury-steak': 'steak',
  'steak-au-poivre': 'steak',
  'steak-bearnaise': 'steak',
  'steak-dinner': 'steak',
  'steak-dish': 'steak',
  'steak-marsala': 'steak',
  'steak-plantains': 'steak',
  'steak-quesadilla': 'steak',
  'steak-taco': 'steak',
  // steak-wrap moved to wraps section
  'steaks': 'steak',
  'tri-tip-steak': 'steak',
  'wagyu-steak': 'steak',
  'flank-steak': 'steak',
  'fried-steak': 'steak',

  // === EGGS ===
  'boiled-eggs': 'eggs',
  'cilbir': 'eggs',
  'deviled-eggs': 'eggs',
  'egg-dish': 'eggs',
  'egg-mcmuffin': 'eggs',
  'egg-scramble': 'eggs',
  'egg-tortilla': 'eggs',
  'egg-yolk': 'eggs',
  'hard-boiled-eggs': 'eggs',
  'hard-cooked-eggs': 'eggs',
  'oeufs-jeannette': 'eggs',
  'truffle-eggs': 'eggs',
  'stir-fried-eggs': 'eggs',
  'frozen-egg-yolks': 'eggs',
  'cured-egg-yolks': 'eggs',
  'pickled-eggs': 'eggs',

  // === POTATO DISHES ===
  'baked-sweet-potato-fries': 'potatoes',
  'buffalo-potatoes': 'potatoes',
  'carne-asada-fries': 'potatoes',
  'curly-fries': 'potatoes',
  'garlic-herb-potatoes': 'potatoes',
  'hash-brown': 'potatoes',
  'hash-brown-waffle': 'potatoes',
  'home-fries': 'potatoes',
  'mash': 'potatoes',
  'mashed-sweet-potatoes': 'potatoes',
  'oven-french-fries': 'potatoes',
  'polenta-fries': 'potatoes',
  'pommes-anna': 'potatoes',
  'potato': 'potatoes',
  'potato-bits': 'potatoes',
  'potato-souffle': 'potatoes',
  'potatoes': 'potatoes',
  'roast-sweet-potatoes': 'potatoes',
  'rosti': 'potatoes',
  'stuffed-potatoes': 'potatoes',
  'sweet-potato-casserole': 'potatoes',
  'sweet-potato-mash': 'potatoes',
  'sweet-potato-muffins': 'potatoes',
  'tater-tots': 'potatoes',
  'bacon-and-potatoes': 'potatoes',

  // === SALADS ===
  'barley-salad': 'salad',
  'blt-salad': 'salad',
  'chopped-salad': 'salad',
  'corn-and-tomato-salad': 'salad',
  'farro-salad': 'salad',
  'green-bean-salad': 'salad',
  'green-papaya-salad': 'salad',
  'green-salad': 'salad',
  'kale-salad-lemon-vinaigrette': 'salad',
  'nicoise-salad': 'salad',
  'noodle-salad': 'salad',
  'panzanella-salad': 'salad',
  'puntarelle-salad': 'salad',
  'summer-salads': 'salad',
  'tuna-salad': 'salad',
  'vegetable-salad': 'salad',
  'wedge-salad': 'salad',
  'cabbage-slaw': 'salad',
  'cole-slaw': 'salad',

  // === DUMPLINGS ===
  'dumplings-with-crispy-wings': 'dumplings',
  'pierogies': 'dumplings',
  'soup-dumpling': 'dumplings',

  // === RICE DISHES ===
  'bibimbap': 'rice-dishes',
  'biryani': 'rice-dishes',
  'chicken-biryani': 'rice-dishes',
  'hyderabadi-biryani': 'rice-dishes',
  'jollof-rice': 'rice-dishes',
  'red-beans-and-rice': 'rice-dishes',
  'tamago-gohan': 'rice-dishes',
  'fusion-rice': 'rice-dishes',
  'risotto': 'rice-dishes',
  'parmesan-risotto': 'rice-dishes',
  'rice-burger': 'rice-dishes',
  'donburi': 'rice-dishes',
  'oyakodon': 'rice-dishes',
  'katsudon': 'rice-dishes',
  'tapsilog': 'rice-dishes',

  // === MEXICAN DISHES ===
  'arepas': 'mexican-latin',
  'arepa': 'mexican-latin',
  'breakfast-burritos': 'burritos',
  'breakfast-taco': 'tacos',
  'burrito-bowl': 'burritos',
  'cemita-sandwich': 'mexican-latin',
  'cheesy-gordita-crunch': 'mexican-latin',
  'chiles-rellenos': 'mexican-latin',
  'chile-verde': 'mexican-latin',
  'chimichanga': 'mexican-latin',
  'chipotle-chicken': 'mexican-latin',
  'cochinita-pibil': 'mexican-latin',
  'crema-de-flor-de-calabasa': 'mexican-latin',
  'crunchwrap': 'mexican-latin',
  'elote': 'mexican-latin',
  'esquites': 'mexican-latin',
  'frijoles-charros': 'mexican-latin',
  'gorditas': 'mexican-latin',
  'gordita-crunch': 'mexican-latin',
  'green-chicken': 'mexican-latin',
  'huevos-al-vapor': 'mexican-latin',
  'lime-cilantro-rice': 'mexican-latin',
  'loaded-nachos': 'nachos',
  'mexican-pizza': 'mexican-latin',
  'mole': 'mexican-latin',
  'nopales-topping': 'mexican-latin',
  'poblano-con-queso': 'mexican-latin',
  'posole': 'mexican-latin',
  'quesatacos': 'tacos',
  'refried-beans': 'mexican-latin',
  'refried-black-beans': 'mexican-latin',
  'street-corn': 'mexican-latin',
  'tacos-dorados': 'tacos',
  'tamales': 'mexican-latin',
  'torta': 'mexican-latin',
  'torta-milanesa': 'mexican-latin',
  'tortilla-chips': 'mexican-latin',
  'tortilla-espanola': 'spanish-dishes',
  'braised-beef-tacos': 'tacos',
  'pulled-pork-tacos': 'tacos',
  'salmon-tacos': 'tacos',
  'choripan': 'mexican-latin',
  'chimichurri-bowl': 'mexican-latin',
  'lomo-al-trapo': 'mexican-latin',

  // === JAPANESE DISHES ===
  'donabe': 'japanese-dishes',
  'japanese-curry': 'japanese-dishes',
  'miso-paste': 'japanese-dishes',
  'okonomiyaki': 'japanese-dishes',
  'pork-shogayaki': 'japanese-dishes',
  'rice-crackers': 'japanese-dishes',
  'rice-koji': 'japanese-dishes',
  'salmon-bowl': 'japanese-dishes',
  'sushi-roll': 'sushi',
  'tempura-vegetables': 'japanese-dishes',
  'teriyaki': 'japanese-dishes',
  'teriyaki-tofu': 'japanese-dishes',
  'tuna-maki': 'sushi',
  'udon-dipping-sauce': 'japanese-dishes',
  'wasabi-ice-cream': 'japanese-dishes',

  // === INDIAN DISHES ===
  'bhaji': 'indian-dishes',
  'chana-masala': 'indian-dishes',
  'dal': 'indian-dishes',
  'ghee': 'indian-dishes',
  'kanji': 'indian-dishes',
  'keema-mutter': 'indian-dishes',
  'khati-roll': 'indian-dishes',
  'kofta': 'indian-dishes',
  'korma': 'indian-dishes',
  'massaman-curry': 'curry',
  'nihari': 'indian-dishes',
  'pakoras': 'indian-dishes',
  'parathas': 'indian-dishes',
  'roti': 'indian-dishes',
  'saag': 'indian-dishes',
  'tikka-masala': 'indian-dishes',
  'vada-pav': 'indian-dishes',

  // === KOREAN DISHES ===
  'bulgogi-hoagies': 'korean-dishes',
  'korean-chicken-wings': 'korean-dishes',
  'korean-stir-fry': 'korean-dishes',
  'tteokbokki': 'korean-dishes',

  // === CHINESE DISHES ===
  // dan-dan-noodles moved to asian-noodles section
  'dry-fried-string-beans': 'chinese-dishes',
  'egg-fried-rice': 'fried-rice',
  'mandarin-pancakes': 'chinese-dishes',
  'rou-jia-mo': 'chinese-dishes',
  'szechuan-eggplant': 'chinese-dishes',

  // === FRENCH DISHES ===
  'cassoulet': 'french-dishes',
  'charcuterie-board': 'french-dishes',
  'clafoutis': 'french-dishes',
  'coq-au-vin': 'french-dishes',
  'crepe-batter': 'crepes',
  'crepe-suzette': 'crepes',
  'crepes-suzette': 'crepes',
  'croque-madame': 'french-dishes',
  'duck-confit': 'french-dishes',
  'escargot': 'french-dishes',
  'french-bread-pizza': 'pizza',
  'french-butter': 'french-dishes',
  'french-omelet': 'omelette',
  'french-tacos': 'french-dishes',

  // === ITALIAN DISHES ===
  'arancini': 'italian-dishes',
  'bruschetta': 'italian-dishes',
  'calzone': 'pizza',
  'eggplant-alla-norma': 'italian-dishes',
  'eggplant-involtini': 'italian-dishes',
  'eggplant-parm': 'italian-dishes',
  'eggplant-parmesan': 'italian-dishes',
  'eggplant-rollatini': 'italian-dishes',
  'osso-buco': 'italian-dishes',
  'roman-pizza-al-taglio': 'pizza',

  // === FRIED FOODS ===
  'blooming-onion': 'fried-foods',
  'fried-olives': 'fried-foods',
  'fried-pies': 'fried-foods',
  'fried-shallots': 'fried-foods',
  'fried-tofu': 'fried-foods',
  'fried-yuca': 'fried-foods',
  'onion-rings': 'fried-foods',
  'fritters': 'fried-foods',

  // === GRILLED DISHES ===
  'grilled-artichokes': 'grilled-dishes',
  'grilled-broccoli': 'grilled-dishes',
  'grilled-burger': 'burger',
  'grilled-burgers': 'burger',
  'grilled-cheese-sandwich': 'grilled-cheese',
  'grilled-chicken-breasts': 'grilled-chicken',
  'grilled-corn': 'grilled-dishes',
  'grilled-ribs': 'grilled-dishes',
  'grilled-sausages': 'grilled-dishes',

  // === ROASTED DISHES ===
  'roast-chicken-with-bread-salad': 'roast-chicken',
  'roasted-broccoli': 'roasted-vegetables',
  'roasted-broccolini': 'roasted-vegetables',
  'roasted-chestnuts': 'roasted-vegetables',
  'roasted-chickpeas': 'roasted-vegetables',
  'roasted-garlic': 'roasted-vegetables',
  'roasted-kale': 'roasted-vegetables',
  'roasted-meat': 'roasted-dishes',
  'roasted-peppers': 'roasted-vegetables',
  'roasted-romanesco': 'roasted-vegetables',

  // === BREAKFAST ===
  'bacon-and-potato-breakfast': 'breakfast',
  'breakfast': 'breakfast',
  'breakfast-baconator': 'breakfast',
  'breakfast-wrap': 'breakfast',
  'biscuits-and-sausage-gravy': 'breakfast',
  'sausage-egg-and-cheese-biscuit': 'breakfast',
  'sausage-gravy-and-biscuits': 'breakfast',
  'mcgriddle': 'breakfast',
  'cereal-bowl': 'breakfast',

  // === TURKEY ===
  'braised-turkey': 'turkey',
  'turkey': 'turkey',
  'turkey-and-gravy': 'turkey',
  'turkey-breast': 'turkey',
  'turkey-burger': 'turkey',
  'turkey-chili': 'turkey',
  'turkey-meatballs': 'turkey',
  'turkey-thighs': 'turkey',
  'stuffed-turkey': 'turkey',
  'cream-of-turkey-soup': 'turkey',

  // === WRAPS ===
  'chicken-wrap': 'wraps',
  'gyro-wrap': 'wraps',
  'lamb-kofta-wrap': 'wraps',
  'snack-wrap': 'wraps',
  'steak-wrap': 'wraps',

  // === TACOS ===
  'fish-tacos': 'tacos',

  // === MISC FAST FOOD ===
  'baconator': 'fast-food',
  'big-mac': 'fast-food',
  'big-mac-pizza': 'fast-food',
  'doritos': 'fast-food',
  'double-down-sandwich': 'fast-food',
  'hot-dogs': 'hot-dog',
  'nacho-cheese-chips': 'fast-food',

  // === DIPS ===
  'queso-dip': 'dips',
  'queso-blanco': 'dips',

  // === ADDITIONAL DESSERTS ===
  // cobbler already defined in desserts section above
  'choux': 'desserts',
  'choux-pastry': 'desserts',
  'fool': 'desserts',
  'cream': 'desserts',
  'meringue': 'desserts',
  'souffle': 'desserts',
  'double-crust-pie': 'desserts',
  'single-crust-pie': 'desserts',
  'pie': 'desserts',
  'pie-crust': 'desserts',
  'pie-dough': 'desserts',
  'tart-dough': 'desserts',
  'crumble-pie': 'desserts',
  'cake-decoration': 'desserts',
  'cake-strip': 'desserts',

  // === VEGETABLES/SIDES ===
  'collard-greens': 'vegetables',
  'greens': 'vegetables',
  'brussels-sprouts': 'vegetables',
  'artichokes': 'vegetables',
  'beets': 'vegetables',
  'zucchini': 'vegetables',
  'eggplant': 'vegetables',
  'vegetables': 'vegetables',
  // roasted-broccoli, roasted-broccolini, roasted-romanesco, roasted-kale moved to roasted-vegetables section
  'smashed-cucumbers': 'vegetables',
  'stir-fried-bok-choy': 'vegetables',
  'stir-fried-broccoli': 'vegetables',
  'stir-fried-broccoli-with-pancetta': 'vegetables',
  'stir-fried-greens': 'vegetables',
  'braised-asparagus': 'vegetables',
  'fava-beans': 'vegetables',
  'corn-ribs': 'vegetables',
  'spaghetti-squash': 'vegetables',

  // === BEANS ===
  'barbecue-beans': 'beans',
  'cooked-beans': 'beans',
  'pinto-beans': 'beans',
  // shrimp-and-beans kept in seafood section

  // === PASTRIES ===
  'croissant-sandwich': 'pastries',
  'donut-croissants': 'pastries',
  'puff-pastry': 'pastries',

  // === ADDITIONAL NOODLES ===
  'dan-dan-noodles': 'asian-noodles',
  'chow-mein': 'asian-noodles',
  'vegetable-lo-mein': 'asian-noodles',

  // === ADDITIONAL PANCAKES ===
  'german-pancake': 'pancakes',
  'dutch-baby': 'pancakes',
  'pancake': 'pancakes',
  // okonomiyaki kept in japanese-dishes section

  // === FISH DISHES ===
  'tandoori-salmon': 'seafood',
  'tagine': 'seafood',
  'smoked-salmon-fish-tacos': 'tacos',

  // === SAVORY PIES ===
  'savory-pie': 'savory-pies',
  'quiche': 'savory-pies',

  // === STUFFED ITEMS ===
  'stuffed-meatballs': 'meatballs',
  'stuffed-peppers': 'stuffed-dishes',
  'stuffed-chicken-breast': 'stuffed-dishes',
  'stuffed-pork-loin': 'stuffed-dishes',
  'stuffed-grape-leaves': 'stuffed-dishes',
  'stuffed-onions': 'stuffed-dishes',
  'stuffed-prosciutto': 'stuffed-dishes',

  // === TARTS ===
  // tart already defined in desserts section above

  // === PRETZELS ===
  'pretzels': 'bread',
  'soft-pretzels': 'bread',

  // === SCONES ===
  'scones': 'bread',

  // === GNOCCHI ===
  'gnocchi-al-forno': 'gnocchi',

  // === KHACHAPURI ===
  'khachapuri': 'bread',

  // === MISC ===
  'simple-syrup': 'sauces',
  'sea-salt': 'seasonings',
  'spice-mix': 'seasonings',
  'dried-herbs': 'seasonings',
  'chili-powder': 'seasonings',
  'seasoning': 'seasonings',
  'smoked-ham': 'pork-dishes',
  'frozen-tofu': 'tofu',
  'butternut-squash-steaks': 'vegetables',
  'cheese-straws': 'appetizers',
  'guanimes': 'mexican-latin',
  'matzo-brei': 'jewish-dishes',
  // matzo-ball-soup kept in soups section
  'matzoh-balls': 'jewish-dishes',
  'pane-francese': 'bread',
  'fried-chicken-wings': 'chicken-wings',

  // === CHEESE ===
  'cheese': 'cheese-dishes',
  'cheese-balls': 'cheese-dishes',
  'cheese-slices': 'cheese-dishes',
  'cream-cheese': 'cheese-dishes',
  'mozzarella-cheese': 'cheese-dishes',
  'vegan-parmesan-cheese': 'cheese-dishes',
  'truffle-cheese': 'cheese-dishes',

  // === KEBABS ===
  'doner-kebab': 'kebabs',
  'doner-kebab-bread': 'kebabs',
  'doner-kebab-chicken': 'kebabs',
  'kebab': 'kebabs',
  'skewers': 'kebabs',
};

/**
 * Canonical names for the broader parent categories
 */
export const PARENT_CATEGORY_NAMES: Record<string, string> = {
  'chicken-dishes': 'Chicken Dishes',
  'beef-dishes': 'Beef Dishes',
  'pork-dishes': 'Pork Dishes',
  'lamb-dishes': 'Lamb Dishes',
  'seafood': 'Seafood',
  'soups': 'Soups',
  'sauces': 'Sauces & Condiments',
  'pasta': 'Pasta',
  'asian-noodles': 'Asian Noodles',
  'bread': 'Bread',
  'desserts': 'Desserts',
  'beverages': 'Beverages',
  'steak': 'Steak',
  'eggs': 'Egg Dishes',
  'potatoes': 'Potato Dishes',
  'salad': 'Salads',
  'dumplings': 'Dumplings',
  'rice-dishes': 'Rice Dishes',
  'mexican-latin': 'Mexican & Latin',
  'japanese-dishes': 'Japanese Dishes',
  'indian-dishes': 'Indian Dishes',
  'korean-dishes': 'Korean Dishes',
  'chinese-dishes': 'Chinese Dishes',
  'french-dishes': 'French Dishes',
  'italian-dishes': 'Italian Dishes',
  'fried-foods': 'Fried Foods',
  'grilled-dishes': 'Grilled Dishes',
  'roasted-vegetables': 'Roasted Vegetables',
  'breakfast': 'Breakfast',
  'turkey': 'Turkey Dishes',
  'wraps': 'Wraps',
  'tacos': 'Tacos',
  'fast-food': 'Fast Food Clones',
  'dips': 'Dips',
  'cheese-dishes': 'Cheese Dishes',
  'kebabs': 'Kebabs',
  'crepes': 'Crepes',
  'burritos': 'Burritos',
  'curry': 'Curry',
  'vegetables': 'Vegetables & Sides',
  'beans': 'Beans',
  'pastries': 'Pastries',
  'savory-pies': 'Savory Pies & Quiche',
  'stuffed-dishes': 'Stuffed Dishes',
  'seasonings': 'Seasonings & Spices',
  'tofu': 'Tofu Dishes',
  'appetizers': 'Appetizers',
  'jewish-dishes': 'Jewish Dishes',
};
